version: '3.1'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "dev"
  app:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:dev@db/pulse"
      HOME: "/"
    volumes:
      - ~/.pulse:/.pulse
    depends_on:
     - db
