version: '3.1'

services:
  app:
    build: .
    volumes:
      - ~/.pulse:/root/.pulse
    ports:
      - 8088:8088
    environment:
      # TODO: Find a way to not have to pass this in - we currently
      #       have to duplicate this both in the config and here
      DATABASE_URL: "postgres://postgres:dev@db"
    depends_on:
     - db
  db:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "dev"
